server:
  port: 8080

spring:
  ai:
    dashscope:
      api-key: YOUR_DASHSCOPE_API_KEY
      chat:
        options:
          model: qwen-turbo
          temperature: 0.7
    deepseek:
      api-key: YOUR_DEEPSEEK_API_KEY
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7 